# Makefile for Fallback.

#=============================================================================#

# Relative path to the directory containing the source code:
SRCDIR := src
# Relative path to the directory that will contain intermediate output files:
OUTDIR := out
# Relative path to the directory that will contain compiled executables:
BINDIR := bin
# Relative path to the directory that will contain documentation:
DOCDIR := doc
# Relative path to the Mac OS X application bundle:
APP_BUNDLE := Fallback.app

# Path to the main binary executable:
MAIN_BIN := $(APP_BUNDLE)/Contents/MacOS/fallback
# Name of the test executable:
TEST_BIN := $(BINDIR)/fallback_test
# The title to use for the documentation:
DOC_TITLE := 'Fallback'

# Flags we want to pass to all invokations of GHC:
GHC_FLAGS := -hidir $(OUTDIR) -odir $(OUTDIR) -stubdir $(OUTDIR) \
	     -i$(SRCDIR) -i$(OUTDIR) -Wall
# For release, add: -O2 -Werror

# List of files to be generated by hsc2hs:
HSC_TARGETS := $(OUTDIR)/Graphics/UI/SDL/Extras.hs
# List of source files to be compiled (other than those in HSC_TARGETS):
HS_FILES := $(shell find $(SRCDIR) -name '*.hs')

SDL_LIBS := \
  /usr/local/lib/libSDL.dylib \
  /usr/local/lib/libSDL_gfx.dylib \
  /usr/local/lib/libSDL_image.dylib \
  /usr/local/lib/libSDL_mixer.dylib \
  /usr/local/lib/libSDL_ttf.dylib

#=============================================================================#

$(MAIN_BIN): $(HSC_TARGETS) $(HS_FILES)
	mkdir -p $(OUTDIR)
	ghc $(GHC_FLAGS) -no-hs-main --make HSMain src/c_main.c -o $@

.PHONY: debug
debug: $(HSC_TARGETS)
	ghci $(GHC_FLAGS) DebugMain $(SDL_LIBS)

$(TEST_BIN): $(HS_FILES)
	mkdir -p $(OUTDIR) $(BINDIR)
	ghc $(GHC_FLAGS) -main-is Test --make Test -o $@

$(HSC_TARGETS): $(OUTDIR)/%.hs: $(SRCDIR)/%.hsc
	mkdir -p `dirname $@`
	hsc2hs -o $@ $<
	sed -e '/^{-# INCLUDE/d' -i '' $@

#=============================================================================#

.PHONY: run
run: $(MAIN_BIN)
	$(MAIN_BIN)

.PHONY: test
test: $(TEST_BIN)
	$(TEST_BIN)

.PHONY: docs
docs: $(HSC_TARGETS)
	mkdir -p $(DOCDIR)
	find $(SRCDIR) $(OUTDIR) -name '*.hs' -print0 | \
	    xargs -0 haddock --html --odir=$(DOCDIR) --title=$(DOC_TITLE)
	open $(DOCDIR)/index.html

.PHONY: clean
clean:
	rm -rf $(OUTDIR) $(BINDIR) $(DOCDIR)
	rm -f $(MAIN_BIN)

.PHONY: tidy
tidy:
	find $(SRCDIR) -name '*~' -print0 | xargs -0 rm
	find pov -name '*~' -print0 | xargs -0 rm

.PHONY: wc
wc:
	find $(SRCDIR) \( -name '*.hs' -or -name '*.hsc' \) -print0 | \
	    xargs -0 wc -l

.PHONY: fixme
fixme:
	ack "FIXME|TODO" $(SRCDIR)

#=============================================================================#
